[LG-62] - add pom extraction process on CI

diff --git a/.github/workflows/c-integration.yml b/.github/workflows/c-integration.yml
--- a/.github/workflows/c-integration.yml
+++ b/.github/workflows/c-integration.yml
@@ -10,6 +10,9 @@ on:
 permissions:
   contents: write
 
+env:
+  MAVEN_DIR: ./
+
 jobs:
   setup:
     name: Setup
@@ -23,6 +26,54 @@ jobs:
         with:
           java-version: 21
           distribution: 'zulu'
+      - name: Install xmllint
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y libxml2-utils
+
+      - name: Check if pom.xml exists
+        run: |
+          if [ ! -f "${{ env.MAVEN_DIR }}/pom.xml" ]; then
+            echo "Error: pom.xml not found in the specified directory: ${{ env.MAVEN_DIR }}"
+            exit 1
+          fi
+
+      - name: Extract Maven coordinates from pom.xml
+        id: extract_maven_coordinates
+        run: |
+          if ! command -v xmllint &> /dev/null; then
+            echo "xmllint could not be found, exiting..."
+            exit 1
+          fi
+          
+          GROUP_ID=$(xmllint --xpath 'string(//*[local-name()="project"]/*[local-name()="groupId"])' pom.xml)
+          ARTIFACT_ID=$(xmllint --xpath 'string(//*[local-name()="project"]/*[local-name()="artifactId"])' pom.xml)
+          VERSION=$(xmllint --xpath 'string(//*[local-name()="project"]/*[local-name()="version"])' pom.xml)
+          IMAGE_NAME="${GROUP_ID}/${ARTIFACT_ID}:${VERSION}"
+          
+          if [[ -z "$GROUP_ID" || -z "$ARTIFACT_ID" || -z "$VERSION" ]]; then
+            echo "Error: One or more Maven coordinates (GROUP_ID, ARTIFACT_ID, VERSION) could not be extracted."
+            exit 1
+          fi
+
+          echo "GROUP_ID=$GROUP_ID" > maven_details.env
+          echo "ARTIFACT_ID=$ARTIFACT_ID" >> maven_details.env
+          echo "VERSION=$VERSION" >> maven_details.env
+          echo "IMAGE_NAME=$IMAGE_NAME" >> maven_details.env
+          
+          echo "image_name_version=$IMAGE_NAME" >> $GITHUB_OUTPUT
+          
+          echo "Extracted GROUP_ID: $GROUP_ID"
+          echo "Extracted ARTIFACT_ID: $ARTIFACT_ID"
+          echo "Extracted VERSION: $VERSION"
+          echo "Extracted IMAGE_NAME: $IMAGE_NAME"
+
+      - name: Upload Maven details artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: maven-details
+          path: maven_details.env
+
       - name: Configure Maven settings.xml
         env:
           GITHUB_USERNAME: ${{ github.actor }}
@@ -157,9 +208,9 @@ jobs:
         run: make install-skip-test
 
       - name: Show docker image
-        run: docker image list | grep com.
+        run: docker image list | grep ${{ needs.setup.outputs.image_name_version }}
       - name: Save Docker image
-        run: docker save -o blank-service-image.tar com.blanksystem/blank-service:1.0.0-alpha
+        run: docker save -o blank-service-image.tar ${{ needs.setup.outputs.image_name_version }}
       - name: Upload Docker image as artifact
         uses: actions/upload-artifact@v4
         with:
@@ -237,7 +288,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Download docker compose
         run: sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-      - name: Permisions to docker compose
+      - name: Permissions to docker compose
         run: sudo chmod +x /usr/local/bin/docker-compose
 
       - name: Generate docs to OpenAPI as html
@@ -259,7 +310,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Download docker compose
         run: sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-      - name: Permisions to docker compose
+      - name: Permissions to docker compose
         run: sudo chmod +x /usr/local/bin/docker-compose
 
       - name: Generate docs to asyncapi as html
