[LG-62] - add validation before publish docker images to xmllint tool

diff --git a/.github/workflows/delivery.yaml b/.github/workflows/delivery.yaml
--- a/.github/workflows/delivery.yaml
+++ b/.github/workflows/delivery.yaml
@@ -19,6 +19,11 @@ jobs:
       - name: Check out the code
         uses: actions/checkout@v4
 
+      - name: Install xmllint
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y libxml2-utils
+
       - name: Download Docker image artifact
         uses: actions/download-artifact@v4
         with:
@@ -44,6 +49,10 @@ jobs:
       - name: Extract Maven coordinates from pom.xml
         id: extract_maven_coordinates
         run: |
+          if ! command -v xmllint &> /dev/null; then
+            echo "xmllint could not be found, exiting..."
+            exit 1
+          fi
           GROUP_ID=$(xmllint --xpath 'string(//project/groupId)' ${{ env.MAVEN_DIR }}/pom.xml | tr '.' '/')  # Cambiar puntos a barras para URL
           ARTIFACT_ID=$(xmllint --xpath 'string(//project/artifactId)' ${{ env.MAVEN_DIR }}/pom.xml)
           VERSION=$(xmllint --xpath 'string(//project/version)' ${{ env.MAVEN_DIR }}/pom.xml)
